# Generated by Django 4.1.2 on 2022-12-06 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 6, 13, 58, 34, 346241, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
