# Generated by Django 4.1.2 on 2022-12-06 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct", "0002_alter_message_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 6, 14, 1, 52, 30363, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
