# Generated by Django 4.1.2 on 2022-12-06 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("direct", "0003_alter_message_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
