# Generated by Django 4.1.2 on 2022-10-24 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0007_remove_volunteer_user_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.PositiveIntegerField(max_length=13, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
