# Generated by Django 4.1.2 on 2022-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Contact Number'),
        ),
    ]
