# Generated by Django 4.1.2 on 2022-10-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_venue_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
