# Generated by Django 4.1.2 on 2022-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0012_volunteer_volunteer"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="venue_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
