# Generated by Django 4.1.2 on 2022-10-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_event_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved',
        ),
    ]
