# Generated by Django 4.1.2 on 2022-11-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_event_event_image'),
        ('planner', '0014_remove_event_approved'),
    ]

    operations = [
    ]
