# Generated by Django 4.1.2 on 2022-11-01 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_merge_20221101_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.event')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.volunteer')),
            ],
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
