# Generated by Django 4.1.2 on 2022-11-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_alter_event_volunteers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submisson',
        ),
    ]
