# Generated by Django 4.1.2 on 2022-11-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0015_merge_20221102_0011"),
        ("planner", "0021_delete_submisson"),
    ]

    operations = []
