# Generated by Django 4.1.2 on 2022-11-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_merge_0015_merge_20221102_0011_0021_delete_submisson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, verbose_name='Event Date'),
        ),
    ]
